import { Campaign, CampaignTypeInfo } from './Campaign.ts'
import { Project, ProjectTypeInfo } from './Project.ts'
import { VirtualAgentDetail, VirtualAgentDetailTypeInfo } from './VirtualAgentDetail.ts'
import { ActionDetail, ActionDetailTypeInfo } from './ActionDetail.ts'
import { CallFlow, CallFlowTypeInfo } from './CallFlow.ts'

export interface CampaignSettingUpdatableProperties {
   readonly ActionCrmId: Id<ActionDetail> | null;
   readonly ActionEmailId: Id<ActionDetail> | null;
   readonly ActionForwardNumberId: Id<ActionDetail> | null;
   readonly ActionInstallmentPlanId: Id<ActionDetail> | null;
   readonly ActionSmsId: Id<ActionDetail> | null;
   readonly CallFlowId: Id<CallFlow> | null;
   readonly ActiveFrom: Date | null;
   readonly ActiveTimeSlotFrom: string | null;
   readonly ActiveTimeSlotTo: string | null;
   readonly ActiveTo: Date | null;
   readonly DebtCollector: string | null;
   readonly HourBetweenRedial: number;
   readonly MaxAttempts: number;
   readonly MaxDays: number;
   readonly NumberOfBots: number | null;
   readonly Priority: number | null;
   readonly VirtualAgentId: Id<VirtualAgentDetail> | null;
   readonly VoiceBotEndpointOverride: string | null;
}

export interface CampaignSettingProperties extends CampaignSettingUpdatableProperties {
   readonly CampaignId: Id<Campaign> | null;
   readonly ProjectId: Id<Project> | null;
}

export interface CampaignSettingAssociations {
   readonly Campaign?: Campaign;
   readonly Project?: Project;
   readonly VirtualAgent?: VirtualAgentDetail;
   readonly ActionCrm?: ActionDetail;
   readonly ActionEmail?: ActionDetail;
   readonly ActionForwardNumber?: ActionDetail;
   readonly ActionInstallmentPlan?: ActionDetail;
   readonly ActionSms?: ActionDetail;
   readonly CallFlow?: CallFlow;
}

export interface CampaignSetting extends CampaignSettingProperties, CampaignSettingAssociations {
   readonly Id: Id<CampaignSetting>;
}

const defaultUpdatableProperties: CampaignSettingUpdatableProperties = {
   ActionCrmId: null,
   ActionEmailId: null,
   ActionForwardNumberId: null,
   ActionInstallmentPlanId: null,
   ActionSmsId: null,
   CallFlowId: null,
   ActiveFrom: null,
   ActiveTimeSlotFrom: null,
   ActiveTimeSlotTo: null,
   ActiveTo: null,
   DebtCollector: null,
   HourBetweenRedial: 0,
   MaxAttempts: 0,
   MaxDays: 0,
   NumberOfBots: null,
   Priority: null,
   VirtualAgentId: null,
   VoiceBotEndpointOverride: null
}

const defaultProperties: CampaignSettingProperties = {
    ...defaultUpdatableProperties,
   CampaignId: null,
   ProjectId: null
}

export const CampaignSettingTypeInfo: IEntityInfo<CampaignSetting, CampaignSettingProperties, CampaignSettingUpdatableProperties, CampaignSettingAssociations> = {
    Name: "CampaignSetting",
    EntityType: {} as CampaignSetting,
    PropertiesType: {} as CampaignSettingProperties,
    UpdatablePropertiesType: {} as CampaignSettingUpdatableProperties,
    Default: defaultProperties,
    DefaultUpdatable: defaultUpdatableProperties,
    AssociationTypeInfos: {
        Campaign: () => CampaignTypeInfo,
        Project: () => ProjectTypeInfo,
        VirtualAgent: () => VirtualAgentDetailTypeInfo,
        ActionCrm: () => ActionDetailTypeInfo,
        ActionEmail: () => ActionDetailTypeInfo,
        ActionForwardNumber: () => ActionDetailTypeInfo,
        ActionInstallmentPlan: () => ActionDetailTypeInfo,
        ActionSms: () => ActionDetailTypeInfo,
        CallFlow: () => CallFlowTypeInfo,
     },
     Properties: {
         Id: {
            Name: "Id", 
            Type: "Id<CampaignSetting>",
            PrimaryKeyOrder: 0,
            IsGeneratedKey: true,
            IsNullable: false,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },

 
         CampaignId: {
            Name: "CampaignId", 
            Type: "Id<Campaign>",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: true,
            IsAssociation: false,
            AssociationType: "Campaign",
            AssociationProp: "Campaign",
        },
        ProjectId: {
            Name: "ProjectId", 
            Type: "Id<Project>",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: true,
            IsAssociation: false,
            AssociationType: "Project",
            AssociationProp: "Project",
        },

         ActionCrmId: {
            Name: "ActionCrmId", 
            Type: "Id<ActionDetail>",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: true,
            IsAssociation: false,
            AssociationType: "ActionDetail",
            AssociationProp: "ActionCrm",
        },
        ActionEmailId: {
            Name: "ActionEmailId", 
            Type: "Id<ActionDetail>",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: true,
            IsAssociation: false,
            AssociationType: "ActionDetail",
            AssociationProp: "ActionEmail",
        },
        ActionForwardNumberId: {
            Name: "ActionForwardNumberId", 
            Type: "Id<ActionDetail>",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: true,
            IsAssociation: false,
            AssociationType: "ActionDetail",
            AssociationProp: "ActionForwardNumber",
        },
        ActionInstallmentPlanId: {
            Name: "ActionInstallmentPlanId", 
            Type: "Id<ActionDetail>",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: true,
            IsAssociation: false,
            AssociationType: "ActionDetail",
            AssociationProp: "ActionInstallmentPlan",
        },
        ActionSmsId: {
            Name: "ActionSmsId", 
            Type: "Id<ActionDetail>",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: true,
            IsAssociation: false,
            AssociationType: "ActionDetail",
            AssociationProp: "ActionSms",
        },
        CallFlowId: {
            Name: "CallFlowId", 
            Type: "Id<CallFlow>",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: true,
            IsAssociation: false,
            AssociationType: "CallFlow",
            AssociationProp: "CallFlow",
        },
        ActiveFrom: {
            Name: "ActiveFrom", 
            Type: "Date",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        ActiveTimeSlotFrom: {
            Name: "ActiveTimeSlotFrom", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        ActiveTimeSlotTo: {
            Name: "ActiveTimeSlotTo", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        ActiveTo: {
            Name: "ActiveTo", 
            Type: "Date",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        DebtCollector: {
            Name: "DebtCollector", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        HourBetweenRedial: {
            Name: "HourBetweenRedial", 
            Type: "number",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        MaxAttempts: {
            Name: "MaxAttempts", 
            Type: "number",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        MaxDays: {
            Name: "MaxDays", 
            Type: "number",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        NumberOfBots: {
            Name: "NumberOfBots", 
            Type: "number",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        Priority: {
            Name: "Priority", 
            Type: "number",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        VirtualAgentId: {
            Name: "VirtualAgentId", 
            Type: "Id<VirtualAgentDetail>",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: true,
            IsAssociation: false,
            AssociationType: "VirtualAgentDetail",
            AssociationProp: "VirtualAgent",
        },
        VoiceBotEndpointOverride: {
            Name: "VoiceBotEndpointOverride", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },

         Campaign: {
            Name: "Campaign", 
            Type: "Campaign",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: true,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        Project: {
            Name: "Project", 
            Type: "Project",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: true,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        VirtualAgent: {
            Name: "VirtualAgent", 
            Type: "VirtualAgentDetail",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: true,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        ActionCrm: {
            Name: "ActionCrm", 
            Type: "ActionDetail",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: true,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        ActionEmail: {
            Name: "ActionEmail", 
            Type: "ActionDetail",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: true,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        ActionForwardNumber: {
            Name: "ActionForwardNumber", 
            Type: "ActionDetail",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: true,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        ActionInstallmentPlan: {
            Name: "ActionInstallmentPlan", 
            Type: "ActionDetail",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: true,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        ActionSms: {
            Name: "ActionSms", 
            Type: "ActionDetail",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: true,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        CallFlow: {
            Name: "CallFlow", 
            Type: "CallFlow",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: true,
            AssociationType: undefined,
            AssociationProp: undefined,
        },

     }
}
