import { Campaign, CampaignTypeInfo } from './Campaign.ts'
import { ContactList, ContactListTypeInfo } from './ContactList.ts'
import { Project, ProjectTypeInfo } from './Project.ts'
import { Phase, PhaseTypeInfo } from './Phase.ts'

export interface ContactUpdatableProperties {
   readonly CurrentPhaseId: Id<Phase> | null;
   readonly AccountNumber: string | null;
   readonly BusinessHours: string | null;
   readonly CallAttempt: number;
   readonly City: string | null;
   readonly Country: string | null;
   readonly CreatedAt: Date;
   readonly Creditor: string | null;
   readonly DateOfBirth: string | null;
   readonly DebtAmount: string | null;
   readonly DebtCollector: string | null;
   readonly DebtDebitor: string | null;
   readonly DebtMaxInstallments: number | null;
   readonly Description: string;
   readonly Email: string | null;
   readonly FirstName: string | null;
   readonly HouseNumber: string | null;
   readonly IsDeleted: boolean;
   readonly IsTestContact: boolean;
   readonly Language: string | null;
   readonly LastName: string | null;
   readonly MiddleName: string | null;
   readonly Name: string;
   readonly NameOfDeceased: string | null;
   readonly NextCallTime: Date | null;
   readonly PropertyCode: string | null;
   readonly SocialSecurityNumber: string | null;
   readonly Status: number | null;
   readonly StreetName: string | null;
   readonly Telephone1: string;
   readonly Telephone2: string | null;
   readonly Telephone3: string | null;
   readonly Telephone4: string | null;
   readonly Zipcode: string | null;
}

export interface ContactProperties extends ContactUpdatableProperties {
   readonly CampaignId: Id<Campaign> | null;
   readonly ContactListId: Id<ContactList>;
   readonly DataJson: string | null;
   readonly ExternalId: string | null;
   readonly MiscInfo1: string | null;
   readonly ProjectId: Id<Project> | null;
   readonly Reference: string | null;
}

export interface ContactAssociations {
   readonly Campaign?: Campaign;
   readonly ContactList?: ContactList;
   readonly Project?: Project;
   readonly CurrentPhase?: Phase;
}

export interface Contact extends ContactProperties, ContactAssociations {
   readonly Id: Id<Contact>;
}

const defaultUpdatableProperties: ContactUpdatableProperties = {
   CurrentPhaseId: null,
   AccountNumber: null,
   BusinessHours: null,
   CallAttempt: 0,
   City: null,
   Country: null,
   CreatedAt: new Date(),
   Creditor: null,
   DateOfBirth: null,
   DebtAmount: null,
   DebtCollector: null,
   DebtDebitor: null,
   DebtMaxInstallments: null,
   Description: '',
   Email: null,
   FirstName: null,
   HouseNumber: null,
   IsDeleted: false,
   IsTestContact: false,
   Language: null,
   LastName: null,
   MiddleName: null,
   Name: '',
   NameOfDeceased: null,
   NextCallTime: null,
   PropertyCode: null,
   SocialSecurityNumber: null,
   Status: null,
   StreetName: null,
   Telephone1: '',
   Telephone2: null,
   Telephone3: null,
   Telephone4: null,
   Zipcode: null
}

const defaultProperties: ContactProperties = {
    ...defaultUpdatableProperties,
   CampaignId: null,
   ContactListId: 0 as Id<ContactList>,
   DataJson: null,
   ExternalId: null,
   MiscInfo1: null,
   ProjectId: null,
   Reference: null
}

export const ContactTypeInfo: IEntityInfo<Contact, ContactProperties, ContactUpdatableProperties, ContactAssociations> = {
    Name: "Contact",
    EntityType: {} as Contact,
    PropertiesType: {} as ContactProperties,
    UpdatablePropertiesType: {} as ContactUpdatableProperties,
    Default: defaultProperties,
    DefaultUpdatable: defaultUpdatableProperties,
    AssociationTypeInfos: {
        Campaign: () => CampaignTypeInfo,
        ContactList: () => ContactListTypeInfo,
        Project: () => ProjectTypeInfo,
        CurrentPhase: () => PhaseTypeInfo,
     },
     Properties: {
         Id: {
            Name: "Id", 
            Type: "Id<Contact>",
            PrimaryKeyOrder: 0,
            IsGeneratedKey: true,
            IsNullable: false,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },

 
         CampaignId: {
            Name: "CampaignId", 
            Type: "Id<Campaign>",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: true,
            IsAssociation: false,
            AssociationType: "Campaign",
            AssociationProp: "Campaign",
        },
        ContactListId: {
            Name: "ContactListId", 
            Type: "Id<ContactList>",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: true,
            IsAssociation: false,
            AssociationType: "ContactList",
            AssociationProp: "ContactList",
        },
        DataJson: {
            Name: "DataJson", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        ExternalId: {
            Name: "ExternalId", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        MiscInfo1: {
            Name: "MiscInfo1", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        ProjectId: {
            Name: "ProjectId", 
            Type: "Id<Project>",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: true,
            IsAssociation: false,
            AssociationType: "Project",
            AssociationProp: "Project",
        },
        Reference: {
            Name: "Reference", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },

         CurrentPhaseId: {
            Name: "CurrentPhaseId", 
            Type: "Id<Phase>",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: true,
            IsAssociation: false,
            AssociationType: "Phase",
            AssociationProp: "CurrentPhase",
        },
        AccountNumber: {
            Name: "AccountNumber", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        BusinessHours: {
            Name: "BusinessHours", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        CallAttempt: {
            Name: "CallAttempt", 
            Type: "number",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        City: {
            Name: "City", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        Country: {
            Name: "Country", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        CreatedAt: {
            Name: "CreatedAt", 
            Type: "Date",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        Creditor: {
            Name: "Creditor", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        DateOfBirth: {
            Name: "DateOfBirth", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        DebtAmount: {
            Name: "DebtAmount", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        DebtCollector: {
            Name: "DebtCollector", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        DebtDebitor: {
            Name: "DebtDebitor", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        DebtMaxInstallments: {
            Name: "DebtMaxInstallments", 
            Type: "number",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        Description: {
            Name: "Description", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        Email: {
            Name: "Email", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        FirstName: {
            Name: "FirstName", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        HouseNumber: {
            Name: "HouseNumber", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        IsDeleted: {
            Name: "IsDeleted", 
            Type: "boolean",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        IsTestContact: {
            Name: "IsTestContact", 
            Type: "boolean",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        Language: {
            Name: "Language", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        LastName: {
            Name: "LastName", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        MiddleName: {
            Name: "MiddleName", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        Name: {
            Name: "Name", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        NameOfDeceased: {
            Name: "NameOfDeceased", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        NextCallTime: {
            Name: "NextCallTime", 
            Type: "Date",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        PropertyCode: {
            Name: "PropertyCode", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        SocialSecurityNumber: {
            Name: "SocialSecurityNumber", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        Status: {
            Name: "Status", 
            Type: "number",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        StreetName: {
            Name: "StreetName", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        Telephone1: {
            Name: "Telephone1", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        Telephone2: {
            Name: "Telephone2", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        Telephone3: {
            Name: "Telephone3", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        Telephone4: {
            Name: "Telephone4", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        Zipcode: {
            Name: "Zipcode", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: true,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },

         Campaign: {
            Name: "Campaign", 
            Type: "Campaign",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: true,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        ContactList: {
            Name: "ContactList", 
            Type: "ContactList",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: true,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        Project: {
            Name: "Project", 
            Type: "Project",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: true,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        CurrentPhase: {
            Name: "CurrentPhase", 
            Type: "Phase",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: true,
            AssociationType: undefined,
            AssociationProp: undefined,
        },

     }
}
