import { CallFlow, CallFlowTypeInfo } from './CallFlow.ts'
import { CommProviderAccount, CommProviderAccountTypeInfo } from './CommProviderAccount.ts'
import { Contact, ContactTypeInfo } from './Contact.ts'
import { InboundNumber, InboundNumberTypeInfo } from './InboundNumber.ts'
import { VirtualAgentDetail, VirtualAgentDetailTypeInfo } from './VirtualAgentDetail.ts'

export interface ContactCallUpdatableProperties {
}

export interface ContactCallProperties extends ContactCallUpdatableProperties {
   readonly CallFlowId: Id<CallFlow> | null;
   readonly CommProviderAccountId: Id<CommProviderAccount> | null;
   readonly ContactId: Id<Contact>;
   readonly Direction: CallDirection;
   readonly InboundNumberId: Id<InboundNumber> | null;
   readonly RemoteNumber: string;
   readonly StartCallRequestAsJson: string | null;
   readonly StartCallResponseAsJson: string | null;
   readonly StartTime: Date;
   readonly TransferNumber: string | null;
   readonly VirtualAgentId: Id<VirtualAgentDetail>;
}

export interface ContactCallAssociations {
   readonly CallFlow?: CallFlow;
   readonly CommProviderAccount?: CommProviderAccount;
   readonly Contact?: Contact;
   readonly InboundNumber?: InboundNumber;
   readonly VirtualAgent?: VirtualAgentDetail;
}

export interface ContactCall extends ContactCallProperties, ContactCallAssociations {
   readonly Id: Id<ContactCall>;
   readonly AnswerTime: Date | null;
   readonly CallConversationTime: number;
   readonly CallDialingTime: number;
   readonly CallMiscInfo1: string | null;
   readonly CallMiscInfo2: string | null;
   readonly CallMiscInfo3: string | null;
   readonly CallMiscInfo4: string | null;
   readonly EndTime: Date | null;
   readonly ExternalCallId: string | null;
   readonly ExternalStatusCodeId: number | null;
   readonly IsRecorded: boolean;
   readonly RecordingUrl: string | null;
   readonly Transcript: string | null;
   readonly TransferTime: Date | null;
   readonly RingingDurationInSeconds: number;
   readonly TransferDurationInSeconds: number;
   readonly VoiceBotDurationInSeconds: number;
}

const defaultUpdatableProperties: ContactCallUpdatableProperties = {

}

const defaultProperties: ContactCallProperties = {
    ...defaultUpdatableProperties,
   CallFlowId: null,
   CommProviderAccountId: null,
   ContactId: 0 as Id<Contact>,
   Direction: '',
   InboundNumberId: null,
   RemoteNumber: '',
   StartCallRequestAsJson: null,
   StartCallResponseAsJson: null,
   StartTime: new Date(),
   TransferNumber: null,
   VirtualAgentId: 0 as Id<VirtualAgentDetail>
}

export const ContactCallTypeInfo: IEntityInfo<ContactCall, ContactCallProperties, ContactCallUpdatableProperties, ContactCallAssociations> = {
    Name: "ContactCall",
    EntityType: {} as ContactCall,
    PropertiesType: {} as ContactCallProperties,
    UpdatablePropertiesType: {} as ContactCallUpdatableProperties,
    Default: defaultProperties,
    DefaultUpdatable: defaultUpdatableProperties,
    AssociationTypeInfos: {
        CallFlow: () => CallFlowTypeInfo,
        CommProviderAccount: () => CommProviderAccountTypeInfo,
        Contact: () => ContactTypeInfo,
        InboundNumber: () => InboundNumberTypeInfo,
        VirtualAgent: () => VirtualAgentDetailTypeInfo,
     },
     Properties: {
         Id: {
            Name: "Id", 
            Type: "Id<ContactCall>",
            PrimaryKeyOrder: 0,
            IsGeneratedKey: true,
            IsNullable: false,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },

         AnswerTime: {
            Name: "AnswerTime", 
            Type: "Date",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        CallConversationTime: {
            Name: "CallConversationTime", 
            Type: "number",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        CallDialingTime: {
            Name: "CallDialingTime", 
            Type: "number",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        CallMiscInfo1: {
            Name: "CallMiscInfo1", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        CallMiscInfo2: {
            Name: "CallMiscInfo2", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        CallMiscInfo3: {
            Name: "CallMiscInfo3", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        CallMiscInfo4: {
            Name: "CallMiscInfo4", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        EndTime: {
            Name: "EndTime", 
            Type: "Date",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        ExternalCallId: {
            Name: "ExternalCallId", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        ExternalStatusCodeId: {
            Name: "ExternalStatusCodeId", 
            Type: "number",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        IsRecorded: {
            Name: "IsRecorded", 
            Type: "boolean",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        RecordingUrl: {
            Name: "RecordingUrl", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        Transcript: {
            Name: "Transcript", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        TransferTime: {
            Name: "TransferTime", 
            Type: "Date",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        RingingDurationInSeconds: {
            Name: "RingingDurationInSeconds", 
            Type: "number",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        TransferDurationInSeconds: {
            Name: "TransferDurationInSeconds", 
            Type: "number",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        VoiceBotDurationInSeconds: {
            Name: "VoiceBotDurationInSeconds", 
            Type: "number",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },

         CallFlowId: {
            Name: "CallFlowId", 
            Type: "Id<CallFlow>",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: true,
            IsAssociation: false,
            AssociationType: "CallFlow",
            AssociationProp: "CallFlow",
        },
        CommProviderAccountId: {
            Name: "CommProviderAccountId", 
            Type: "Id<CommProviderAccount>",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: true,
            IsAssociation: false,
            AssociationType: "CommProviderAccount",
            AssociationProp: "CommProviderAccount",
        },
        ContactId: {
            Name: "ContactId", 
            Type: "Id<Contact>",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: true,
            IsAssociation: false,
            AssociationType: "Contact",
            AssociationProp: "Contact",
        },
        Direction: {
            Name: "Direction", 
            Type: "CallDirection",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        InboundNumberId: {
            Name: "InboundNumberId", 
            Type: "Id<InboundNumber>",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: true,
            IsAssociation: false,
            AssociationType: "InboundNumber",
            AssociationProp: "InboundNumber",
        },
        RemoteNumber: {
            Name: "RemoteNumber", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        StartCallRequestAsJson: {
            Name: "StartCallRequestAsJson", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        StartCallResponseAsJson: {
            Name: "StartCallResponseAsJson", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        StartTime: {
            Name: "StartTime", 
            Type: "Date",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        TransferNumber: {
            Name: "TransferNumber", 
            Type: "string",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: false,
            IsAssociation: false,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        VirtualAgentId: {
            Name: "VirtualAgentId", 
            Type: "Id<VirtualAgentDetail>",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: false,
            IsUpdatable: false,
            IsInsertable: true,
            IsAssociationId: true,
            IsAssociation: false,
            AssociationType: "VirtualAgentDetail",
            AssociationProp: "VirtualAgent",
        },

 
         CallFlow: {
            Name: "CallFlow", 
            Type: "CallFlow",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: true,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        CommProviderAccount: {
            Name: "CommProviderAccount", 
            Type: "CommProviderAccount",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: true,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        Contact: {
            Name: "Contact", 
            Type: "Contact",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: true,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        InboundNumber: {
            Name: "InboundNumber", 
            Type: "InboundNumber",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: true,
            AssociationType: undefined,
            AssociationProp: undefined,
        },
        VirtualAgent: {
            Name: "VirtualAgent", 
            Type: "VirtualAgentDetail",
            PrimaryKeyOrder: null,
            IsGeneratedKey: false,
            IsNullable: true,
            IsUpdatable: false,
            IsInsertable: false,
            IsAssociationId: false,
            IsAssociation: true,
            AssociationType: undefined,
            AssociationProp: undefined,
        },

     }
}
